### ISSUE TITLE
Mocha 프레임워크 대응

### ISSUE THREAD

**Issue by kimploo** [codestates/assignment-manager#3]
## 문제상황

아래 리포지토리에서 테스트를 모카 프레임워크로 진행하여 `codestates-assignment-manager`를 적용할 수 없다.

유닛 | 스프린트 | Repo URL
-- | -- | --
[인증/보안] 기초 | Session | https://github.com/codestates/im-sprint-auth-session
[인증/보안] 기초 | Token | https://github.com/codestates/im-sprint-auth-token
[인증/보안] 기초 | OAuth | https://github.com/codestates/im-sprint-auth-oauth

## TODO

- [ ] [imposter-reporter](https://github.com/codestates/assignment-manager/blob/main/imposter-reporter/index.js)가 모카 프레임워크의 `"@mochajs/json-file-reporter": "^1.3.0"`의 리포트 데이터도 저장할 수 있어야 한다.

**Comment by hongsw** [comment]
https://github.com/codestates/assignment-manager/commit/f044a78cd5ed9dcf50888f688f65be7fe2f6467f
close #3
